# Course info
course:
  name: Назва Курсу
  professors:

    - name: Делоне Б. М.
      avatar_url: https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png
      email: delaunay.boris@google.com
      calendar_link: "#"
      lectures: true
      practice: true

    - name: Боголюбов М. М.
      avatar_url: https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png
      email: delaunay.boris@google.com
      calendar_link: "#"
      lectures: false
      practice: true

# Site configurations
sass:
  sass_dir: _sass
