# Site info (this SHOULD match your Github's repository name)
baseurl: /Starter

# Course info
course:
  name: Назва Курсу
  professors:

    - name: Делоне Борис Михайлович
      avatar_url: https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png
      email: delaunay@google.com
      calendar_link: "#"
      lectures: true
      practice: true

    - name: Боголюбов Микола Миколайович
      avatar_url: https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png
      email: bogolyubov@google.com
      calendar_link: "#"
      lectures: false
      practice: true

# Site configurations
sass:
  sass_dir: _sass
